// @generated by stern-spec; do not edit.
//
// Provenance (vendoring metadata; not part of the generated output):
// - Source: stern-design-system repository,
//   `generated/rust/stern_tokens.rs` (checked out as a sibling of the stern
//   workspace root: `../stern-design-system/generated/rust/stern_tokens.rs`).
// - Vendored: 2026-08-03.
// - SOURCE_SHA256: f1d489f6f28b613c0bcfa4490b7855da341457ee20c66c892dc37ebff2d024ed
// - Do not edit; re-vendor from stern-design-system. The drift test in
//   `crate::theme::tests` fails when this copy no longer matches the
//   design-system output.

//! Design-system tokens generated by `stern-spec` and vendored verbatim from
//! the read-only `stern-design-system` repository.
//!
//! This module is the staging ground for adopting the design-system token
//! pipeline. The hand-rolled values in [`crate::theme`] remain the runtime
//! source of truth while adoption is staged; mappings are verified against
//! these constants one group at a time (accent colors first).
#![allow(missing_docs)] // Generated file: items intentionally carry no docs.
#![allow(clippy::pedantic)] // Generated file: kept verbatim from upstream.

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct NamedColor { pub name: &'static str, pub value: &'static str }

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct NamedMetric { pub name: &'static str, pub value: f32 }

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct NamedString { pub name: &'static str, pub value: &'static str }

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct IconMapping { pub id: &'static str, pub phosphor_name: &'static str, pub default_weight: &'static str }

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct FontFamily { pub role: &'static str, pub primary: &'static str, pub fallbacks: &'static [&'static str] }

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ColorSpaceDescriptor { pub id: &'static str, pub primaries: &'static str, pub transfer_function: &'static str, pub white_point: &'static str }

pub const STERN_VERSION: &str = "1.0.0-rc.2.dev";
pub const SOURCE_SHA256: &str = "f1d489f6f28b613c0bcfa4490b7855da341457ee20c66c892dc37ebff2d024ed";

pub const COLORS: &[NamedColor] = &[
    NamedColor { name: "color.accent.default", value: "#0C8CE9" },
    NamedColor { name: "color.accent.focus", value: "#4DB2FF" },
    NamedColor { name: "color.accent.foreground", value: "#FFFFFF" },
    NamedColor { name: "color.accent.hover", value: "#259CF0" },
    NamedColor { name: "color.accent.pressed", value: "#0876C5" },
    NamedColor { name: "color.accent.subtle", value: "#0B2A3F" },
    NamedColor { name: "color.neutral.0", value: "#FFFFFF" },
    NamedColor { name: "color.neutral.100", value: "#E8E8E8" },
    NamedColor { name: "color.neutral.1000", value: "#0B0B0B" },
    NamedColor { name: "color.neutral.300", value: "#B8B8B8" },
    NamedColor { name: "color.neutral.400", value: "#999999" },
    NamedColor { name: "color.neutral.500", value: "#666666" },
    NamedColor { name: "color.neutral.600", value: "#3D3D3D" },
    NamedColor { name: "color.neutral.700", value: "#2A2A2A" },
    NamedColor { name: "color.neutral.750", value: "#222222" },
    NamedColor { name: "color.neutral.800", value: "#1C1C1C" },
    NamedColor { name: "color.neutral.850", value: "#181818" },
    NamedColor { name: "color.neutral.900", value: "#141414" },
    NamedColor { name: "color.neutral.950", value: "#111111" },
    NamedColor { name: "color.semantic.border.default", value: "#2A2A2A" },
    NamedColor { name: "color.semantic.border.disabled", value: "#222222" },
    NamedColor { name: "color.semantic.border.focused", value: "#4DB2FF" },
    NamedColor { name: "color.semantic.border.hover", value: "#3D3D3D" },
    NamedColor { name: "color.semantic.border.invalid", value: "#F18A90" },
    NamedColor { name: "color.semantic.border.strong", value: "#3D3D3D" },
    NamedColor { name: "color.semantic.border.subtle", value: "#222222" },
    NamedColor { name: "color.semantic.content.disabled", value: "#666666" },
    NamedColor { name: "color.semantic.content.link", value: "#259CF0" },
    NamedColor { name: "color.semantic.content.muted", value: "#999999" },
    NamedColor { name: "color.semantic.content.on_accent", value: "#FFFFFF" },
    NamedColor { name: "color.semantic.content.primary", value: "#E8E8E8" },
    NamedColor { name: "color.semantic.content.secondary", value: "#B8B8B8" },
    NamedColor { name: "color.semantic.focus.indicator", value: "#4DB2FF" },
    NamedColor { name: "color.semantic.focus.ring", value: "#4DB2FF" },
    NamedColor { name: "color.semantic.focus.separator", value: "#0B0B0B" },
    NamedColor { name: "color.semantic.overlay.scrim", value: "#0B0B0B" },
    NamedColor { name: "color.semantic.selection.background", value: "#0C8CE9" },
    NamedColor { name: "color.semantic.selection.foreground", value: "#FFFFFF" },
    NamedColor { name: "color.semantic.surface.application", value: "#111111" },
    NamedColor { name: "color.semantic.surface.control", value: "#181818" },
    NamedColor { name: "color.semantic.surface.control_disabled", value: "#141414" },
    NamedColor { name: "color.semantic.surface.control_hover", value: "#1C1C1C" },
    NamedColor { name: "color.semantic.surface.control_pressed", value: "#2A2A2A" },
    NamedColor { name: "color.semantic.surface.hover", value: "#1C1C1C" },
    NamedColor { name: "color.semantic.surface.overlay", value: "#181818" },
    NamedColor { name: "color.semantic.surface.panel", value: "#141414" },
    NamedColor { name: "color.semantic.surface.panel_raised", value: "#181818" },
    NamedColor { name: "color.semantic.surface.raised", value: "#181818" },
    NamedColor { name: "color.semantic.surface.sunken", value: "#0B0B0B" },
    NamedColor { name: "color.semantic.surface.workspace", value: "#0B0B0B" },
    NamedColor { name: "color.status.danger.border", value: "#3D292B" },
    NamedColor { name: "color.status.danger.foreground", value: "#F18A90" },
    NamedColor { name: "color.status.danger.strong", value: "#D9535B" },
    NamedColor { name: "color.status.danger.surface", value: "#1B1314" },
    NamedColor { name: "color.status.info.border", value: "#25343F" },
    NamedColor { name: "color.status.info.foreground", value: "#6CBFFF" },
    NamedColor { name: "color.status.info.strong", value: "#0C8CE9" },
    NamedColor { name: "color.status.info.surface", value: "#101820" },
    NamedColor { name: "color.status.success.border", value: "#29372E" },
    NamedColor { name: "color.status.success.foreground", value: "#72D998" },
    NamedColor { name: "color.status.success.strong", value: "#39B868" },
    NamedColor { name: "color.status.success.surface", value: "#121A15" },
    NamedColor { name: "color.status.warning.border", value: "#3A3326" },
    NamedColor { name: "color.status.warning.foreground", value: "#F0C66D" },
    NamedColor { name: "color.status.warning.strong", value: "#D9A441" },
    NamedColor { name: "color.status.warning.surface", value: "#1A1711" },
];

pub const SPACING: &[NamedMetric] = &[
    NamedMetric { name: "spacing.0", value: 0.0 },
    NamedMetric { name: "spacing.1", value: 2.0 },
    NamedMetric { name: "spacing.2", value: 4.0 },
    NamedMetric { name: "spacing.3", value: 6.0 },
    NamedMetric { name: "spacing.4", value: 8.0 },
    NamedMetric { name: "spacing.5", value: 12.0 },
    NamedMetric { name: "spacing.6", value: 16.0 },
    NamedMetric { name: "spacing.7", value: 24.0 },
    NamedMetric { name: "spacing.8", value: 32.0 },
    NamedMetric { name: "spacing.gap.control_tight", value: 4.0 },
    NamedMetric { name: "spacing.gap.group", value: 8.0 },
    NamedMetric { name: "spacing.gap.icon_label", value: 4.0 },
    NamedMetric { name: "spacing.gap.inspector_label_value", value: 8.0 },
    NamedMetric { name: "spacing.gap.section", value: 16.0 },
    NamedMetric { name: "spacing.padding.control.block", value: 4.0 },
    NamedMetric { name: "spacing.padding.control.inline.compact", value: 6.0 },
    NamedMetric { name: "spacing.padding.control.inline.default", value: 8.0 },
    NamedMetric { name: "spacing.padding.panel", value: 8.0 },
];

pub const RADII: &[NamedMetric] = &[
    NamedMetric { name: "radius.full", value: 9999.0 },
    NamedMetric { name: "radius.lg", value: 12.0 },
    NamedMetric { name: "radius.md", value: 6.0 },
    NamedMetric { name: "radius.none", value: 0.0 },
    NamedMetric { name: "radius.sm", value: 3.0 },
];

pub const SIZES: &[NamedMetric] = &[
    NamedMetric { name: "size.control.lg", value: 32.0 },
    NamedMetric { name: "size.control.md", value: 28.0 },
    NamedMetric { name: "size.control.sm", value: 24.0 },
    NamedMetric { name: "size.control.xs", value: 20.0 },
    NamedMetric { name: "size.handle.hit", value: 7.0 },
    NamedMetric { name: "size.handle.visual", value: 1.0 },
    NamedMetric { name: "size.icon.lg", value: 20.0 },
    NamedMetric { name: "size.icon.md", value: 16.0 },
    NamedMetric { name: "size.icon.sm", value: 12.0 },
    NamedMetric { name: "size.panelHeader", value: 30.0 },
    NamedMetric { name: "size.row.compact", value: 24.0 },
    NamedMetric { name: "size.row.standard", value: 28.0 },
    NamedMetric { name: "size.tab", value: 28.0 },
    NamedMetric { name: "size.workspaceBar", value: 40.0 },
];

pub const STROKES: &[NamedMetric] = &[
    NamedMetric { name: "stroke.default", value: 1.0 },
    NamedMetric { name: "stroke.emphasis", value: 2.0 },
    NamedMetric { name: "stroke.focus.primary", value: 1.0 },
    NamedMetric { name: "stroke.focus.separator", value: 1.0 },
    NamedMetric { name: "stroke.hairline", value: 1.0 },
];

pub const DURATIONS_MS: &[NamedMetric] = &[
    NamedMetric { name: "durationMs.fast", value: 80.0 },
    NamedMetric { name: "durationMs.instant", value: 0.0 },
    NamedMetric { name: "durationMs.normal", value: 120.0 },
    NamedMetric { name: "durationMs.slow", value: 180.0 },
];

pub const ELEVATION: &[NamedMetric] = &[
    NamedMetric { name: "elevation.high", value: 3.0 },
    NamedMetric { name: "elevation.low", value: 1.0 },
    NamedMetric { name: "elevation.medium", value: 2.0 },
    NamedMetric { name: "elevation.none", value: 0.0 },
];

pub const FOCUS_INDICATOR_WIDTH: f32 = 1.0;
pub const FOCUS_SEPARATOR_WIDTH: f32 = 1.0;
pub const FOCUS_CHANGES_LAYOUT_BOUNDS: bool = false;

pub const EASINGS: &[NamedString] = &[
    NamedString { name: "easing.exit", value: "cubic-bezier(0.4, 0, 1, 1)" },
    NamedString { name: "easing.standard", value: "cubic-bezier(0.2, 0, 0, 1)" },
];

pub const SHADOWS: &[NamedString] = &[
    NamedString { name: "shadow.high", value: "0 12px 36px 0 rgb(0 0 0 / 52%)" },
    NamedString { name: "shadow.low", value: "0 2px 6px 0 rgb(0 0 0 / 32%)" },
    NamedString { name: "shadow.medium", value: "0 6px 18px 0 rgb(0 0 0 / 42%)" },
    NamedString { name: "shadow.none", value: "none" },
];

pub const FONT_FAMILIES: &[FontFamily] = &[
    FontFamily { role: "ui", primary: "Inter", fallbacks: &["Segoe UI Variable Text", "Segoe UI", "system-ui", "sans-serif"] },
    FontFamily { role: "brand", primary: "Space Grotesk", fallbacks: &["Inter", "Segoe UI", "system-ui", "sans-serif"] },
    FontFamily { role: "mono", primary: "Space Mono", fallbacks: &["ui-monospace", "SFMono-Regular", "Consolas", "monospace"] },
];

pub const ICON_SOURCE_VERSION: &str = "2.1.2";
pub const ICONS: &[IconMapping] = &[
    IconMapping { id: "add", phosphor_name: "plus", default_weight: "regular" },
    IconMapping { id: "check", phosphor_name: "check", default_weight: "regular" },
    IconMapping { id: "close", phosphor_name: "x", default_weight: "regular" },
    IconMapping { id: "delete", phosphor_name: "trash", default_weight: "regular" },
    IconMapping { id: "disclosure", phosphor_name: "caret-right", default_weight: "regular" },
    IconMapping { id: "drag", phosphor_name: "hand-grabbing", default_weight: "regular" },
    IconMapping { id: "dropdown", phosphor_name: "caret-down", default_weight: "regular" },
    IconMapping { id: "graph", phosphor_name: "graph", default_weight: "regular" },
    IconMapping { id: "maximize", phosphor_name: "square", default_weight: "regular" },
    IconMapping { id: "minimize", phosphor_name: "minus", default_weight: "regular" },
    IconMapping { id: "more", phosphor_name: "dots-three", default_weight: "regular" },
    IconMapping { id: "pause", phosphor_name: "pause", default_weight: "fill" },
    IconMapping { id: "play", phosphor_name: "play", default_weight: "fill" },
    IconMapping { id: "redo", phosphor_name: "arrow-clockwise", default_weight: "regular" },
    IconMapping { id: "reset", phosphor_name: "arrow-counter-clockwise", default_weight: "regular" },
    IconMapping { id: "search", phosphor_name: "magnifying-glass", default_weight: "regular" },
    IconMapping { id: "settings", phosphor_name: "sliders-horizontal", default_weight: "regular" },
    IconMapping { id: "timeline", phosphor_name: "film-strip", default_weight: "regular" },
    IconMapping { id: "undo", phosphor_name: "arrow-counter-clockwise", default_weight: "regular" },
    IconMapping { id: "warning", phosphor_name: "warning", default_weight: "fill" },
];

pub const COLOR_SPACES: &[ColorSpaceDescriptor] = &[
    ColorSpaceDescriptor { id: "display-p3", primaries: "display-p3", transfer_function: "srgb", white_point: "D65" },
    ColorSpaceDescriptor { id: "linear-srgb", primaries: "srgb", transfer_function: "linear", white_point: "D65" },
    ColorSpaceDescriptor { id: "srgb", primaries: "srgb", transfer_function: "srgb", white_point: "D65" },
];
