//! Platform-independent accessibility semantics.

use std::collections::{BTreeMap, BTreeSet};

use crate::{ActionDescriptor, ActionId, Rect, WidgetId};

/// Semantic role exposed by a UI node.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum SemanticRole {
    /// Application or document root.
    Root,
    /// Dock that owns frames.
    Dock,
    /// Docked frame container.
    Frame,
    /// Passive panel or inspector region.
    Panel,
    /// Static label text.
    Label,
    /// Push button.
    Button,
    /// Icon-only button.
    IconButton,
    /// Checkbox control.
    CheckBox,
    /// Radio button control.
    RadioButton,
    /// Toggle/switch control.
    Toggle,
    /// Slider control.
    Slider,
    /// Single-line or multi-line text field.
    TextField,
    /// Search field.
    SearchField,
    /// Static image.
    Image,
    /// Virtual or concrete list.
    List,
    /// List item.
    ListItem,
    /// Grid collection.
    Grid,
    /// Data table.
    Table,
    /// Table row.
    Row,
    /// Table cell.
    Cell,
    /// Tab list.
    TabList,
    /// Tab header.
    Tab,
    /// Menu surface.
    Menu,
    /// Menu item.
    MenuItem,
    /// Command palette surface.
    CommandPalette,
    /// Media, video, image, or 3D viewport.
    Viewport,
    /// Application-defined role.
    Custom(String),
}

/// Value attached to semantic controls such as sliders and text fields.
#[derive(Debug, Clone, PartialEq)]
pub enum SemanticValue {
    /// Text value.
    Text(String),
    /// Numeric value with inclusive bounds.
    Number {
        /// Current value.
        current: f32,
        /// Minimum allowed value.
        min: f32,
        /// Maximum allowed value.
        max: f32,
    },
}

/// Runtime semantic state for a node.
#[derive(Debug, Clone, Default, PartialEq)]
#[allow(clippy::struct_excessive_bools)]
pub struct SemanticState {
    /// Node cannot currently be operated.
    pub disabled: bool,
    /// Node owns keyboard focus.
    pub focused: bool,
    /// Node is selected.
    pub selected: bool,
    /// Node is checked, when the role supports checked state.
    pub checked: Option<bool>,
    /// Node is expanded, when the role supports disclosure state.
    pub expanded: Option<bool>,
    /// Node is actively pressed.
    pub pressed: bool,
    /// Node value.
    pub value: Option<SemanticValue>,
}

/// Accessibility action kind supported by a semantic node.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum SemanticActionKind {
    /// Invoke the default action.
    Invoke,
    /// Move keyboard focus to the node.
    Focus,
    /// Increment a value.
    Increment,
    /// Decrement a value.
    Decrement,
    /// Set a numeric value.
    SetValue,
    /// Set text content.
    SetText,
    /// Open a popup or disclosure.
    Open,
    /// Close a popup or disclosure.
    Close,
    /// Dismiss an overlay.
    Dismiss,
    /// Application-defined action.
    Custom(String),
}

/// Semantic action exposed on a node.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SemanticAction {
    /// Action kind.
    pub kind: SemanticActionKind,
    /// Human-readable action label.
    pub label: String,
    /// Optional application action identity.
    pub action_id: Option<ActionId>,
}

impl SemanticAction {
    /// Creates a semantic action.
    #[must_use]
    pub fn new(kind: SemanticActionKind, label: impl Into<String>) -> Self {
        Self {
            kind,
            label: label.into(),
            action_id: None,
        }
    }

    /// Creates an invoke action from an application action descriptor.
    #[must_use]
    pub fn from_action_descriptor(descriptor: &ActionDescriptor) -> Self {
        Self {
            kind: SemanticActionKind::Invoke,
            label: descriptor.label.clone(),
            action_id: Some(descriptor.id.clone()),
        }
    }
}

/// Semantic node generated by UI code.
#[derive(Debug, Clone, PartialEq)]
pub struct SemanticNode {
    /// Stable widget identity.
    pub id: WidgetId,
    /// Semantic role.
    pub role: SemanticRole,
    /// Logical bounds.
    pub bounds: Rect,
    /// Accessible name.
    pub label: Option<String>,
    /// Longer accessible description.
    pub description: Option<String>,
    /// Runtime state.
    pub state: SemanticState,
    /// Supported semantic actions.
    pub actions: Vec<SemanticAction>,
    /// Ordered child node IDs.
    pub children: Vec<WidgetId>,
    /// Whether the node participates in focus traversal.
    pub focusable: bool,
}

impl SemanticNode {
    /// Creates a semantic node.
    #[must_use]
    pub fn new(id: WidgetId, role: SemanticRole, bounds: Rect) -> Self {
        Self {
            id,
            role,
            bounds,
            label: None,
            description: None,
            state: SemanticState::default(),
            actions: Vec::new(),
            children: Vec::new(),
            focusable: false,
        }
    }

    /// Assigns an accessible label.
    #[must_use]
    pub fn with_label(mut self, label: impl Into<String>) -> Self {
        self.label = Some(label.into());
        self
    }

    /// Marks the node as focusable and adds a focus action.
    #[must_use]
    pub fn focusable(mut self, focusable: bool) -> Self {
        self.focusable = focusable;
        if focusable
            && !self
                .actions
                .iter()
                .any(|action| action.kind == SemanticActionKind::Focus)
        {
            self.actions
                .push(SemanticAction::new(SemanticActionKind::Focus, "Focus"));
        }
        self
    }

    /// Adds a supported action.
    #[must_use]
    pub fn with_action(mut self, action: SemanticAction) -> Self {
        self.actions.push(action);
        self
    }

    /// Adds child node IDs in visual order.
    #[must_use]
    pub fn with_children(mut self, children: impl IntoIterator<Item = WidgetId>) -> Self {
        self.children.extend(children);
        self
    }
}

/// Semantic tree for one UI frame.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct SemanticTree {
    nodes: Vec<SemanticNode>,
    root: Option<WidgetId>,
}

impl SemanticTree {
    /// Creates an empty semantic tree.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Sets the root node ID.
    pub fn set_root(&mut self, root: WidgetId) {
        self.root = Some(root);
    }

    /// Returns true when the tree contains no semantic nodes.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.nodes.is_empty()
    }

    /// Returns the number of semantic nodes in the tree.
    #[must_use]
    pub fn len(&self) -> usize {
        self.nodes.len()
    }

    /// Returns the root node ID.
    #[must_use]
    pub const fn root(&self) -> Option<WidgetId> {
        self.root
    }

    /// Pushes a node in traversal order.
    pub fn push(&mut self, node: SemanticNode) {
        if self.root.is_none() {
            self.root = Some(node.id);
        }
        self.nodes.push(node);
    }

    /// Returns all nodes in insertion order.
    #[must_use]
    pub fn nodes(&self) -> &[SemanticNode] {
        &self.nodes
    }

    /// Finds a node by ID.
    #[must_use]
    pub fn get(&self, id: WidgetId) -> Option<&SemanticNode> {
        self.nodes.iter().find(|node| node.id == id)
    }

    /// Returns the parent node ID for a child.
    #[must_use]
    pub fn parent_of(&self, child: WidgetId) -> Option<WidgetId> {
        self.nodes
            .iter()
            .find(|node| node.children.contains(&child))
            .map(|node| node.id)
    }

    /// Returns node IDs in semantic child order, appending unparented nodes in insertion order.
    #[must_use]
    pub fn traversal_order(&self) -> Vec<WidgetId> {
        let mut order = Vec::new();
        let mut visited = BTreeSet::new();
        if let Some(root) = self.root.filter(|root| self.get(*root).is_some()) {
            self.push_traversal(root, &mut visited, &mut order);
        }
        for node in &self.nodes {
            self.push_traversal(node.id, &mut visited, &mut order);
        }
        order
    }

    /// Returns focusable node IDs in traversal order.
    #[must_use]
    pub fn focus_order(&self) -> Vec<WidgetId> {
        self.traversal_order()
            .into_iter()
            .filter(|id| {
                self.get(*id)
                    .is_some_and(|node| node.focusable && !node.state.disabled)
            })
            .collect()
    }

    /// Exports a validated accessibility snapshot for platform adapters.
    ///
    /// # Errors
    ///
    /// Returns [`SemanticTreeError`] when the semantic tree is structurally
    /// invalid.
    pub fn accessibility_snapshot(
        &self,
        focused: Option<WidgetId>,
    ) -> Result<AccessibilitySnapshot, SemanticTreeError> {
        AccessibilitySnapshot::from_tree(self, focused)
    }

    /// Validates structural semantic-tree invariants.
    ///
    /// Empty trees are valid. Non-empty trees must have a root that points at
    /// an existing node, unique node IDs, children that point at existing
    /// nodes, and no node may have multiple semantic parents.
    ///
    /// # Errors
    ///
    /// Returns [`SemanticTreeError`] for the first structural violation found.
    pub fn validate(&self) -> Result<(), SemanticTreeError> {
        if self.nodes.is_empty() {
            return Ok(());
        }

        let mut ids = BTreeSet::new();
        for node in &self.nodes {
            if !ids.insert(node.id) {
                return Err(SemanticTreeError::DuplicateNodeId { id: node.id });
            }
        }

        let Some(root) = self.root else {
            return Err(SemanticTreeError::MissingRoot);
        };
        if !ids.contains(&root) {
            return Err(SemanticTreeError::UnknownRoot { id: root });
        }

        let mut parent_by_child = BTreeMap::new();
        let mut children_by_parent = BTreeMap::new();
        for node in &self.nodes {
            let mut child_ids = BTreeSet::new();
            for child in &node.children {
                if *child == node.id {
                    return Err(SemanticTreeError::SelfChild { id: node.id });
                }
                if !ids.contains(child) {
                    return Err(SemanticTreeError::UnknownChild {
                        parent: node.id,
                        child: *child,
                    });
                }
                if !child_ids.insert(*child) {
                    return Err(SemanticTreeError::DuplicateChild {
                        parent: node.id,
                        child: *child,
                    });
                }
                if let Some(first_parent) = parent_by_child.insert(*child, node.id) {
                    return Err(SemanticTreeError::MultipleParents {
                        child: *child,
                        first_parent,
                        second_parent: node.id,
                    });
                }
            }
            children_by_parent.insert(node.id, node.children.clone());
        }

        let mut visited = BTreeSet::new();
        let mut visiting = BTreeSet::new();
        validate_semantic_cycles(root, &children_by_parent, &mut visiting, &mut visited)?;
        for node in &self.nodes {
            validate_semantic_cycles(node.id, &children_by_parent, &mut visiting, &mut visited)?;
        }

        Ok(())
    }

    fn push_traversal(
        &self,
        id: WidgetId,
        visited: &mut BTreeSet<WidgetId>,
        order: &mut Vec<WidgetId>,
    ) {
        if !visited.insert(id) {
            return;
        }
        let Some(node) = self.get(id) else {
            return;
        };
        order.push(id);
        for child in &node.children {
            self.push_traversal(*child, visited, order);
        }
    }
}

/// Structural semantic tree validation error.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SemanticTreeError {
    /// Non-empty tree has no root node.
    MissingRoot,
    /// Root points at a node that is not present in the tree.
    UnknownRoot {
        /// Unknown root node ID.
        id: WidgetId,
    },
    /// Two nodes use the same stable node ID.
    DuplicateNodeId {
        /// Duplicate node ID.
        id: WidgetId,
    },
    /// A child edge points at a node that is not present in the tree.
    UnknownChild {
        /// Parent node ID.
        parent: WidgetId,
        /// Unknown child node ID.
        child: WidgetId,
    },
    /// A node lists the same child more than once.
    DuplicateChild {
        /// Parent node ID.
        parent: WidgetId,
        /// Duplicate child node ID.
        child: WidgetId,
    },
    /// A node lists itself as a child.
    SelfChild {
        /// Self-referential node ID.
        id: WidgetId,
    },
    /// A child has more than one semantic parent.
    MultipleParents {
        /// Child node ID.
        child: WidgetId,
        /// First parent encountered.
        first_parent: WidgetId,
        /// Second parent encountered.
        second_parent: WidgetId,
    },
    /// A semantic child cycle was detected.
    Cycle {
        /// Node where the cycle was detected.
        id: WidgetId,
    },
}

/// Semantic node data exported to platform accessibility adapters.
///
/// This is the stable, backend-neutral data contract for adapters. It is
/// derived from a validated [`SemanticTree`] and does not carry render
/// primitive or platform API state.
#[derive(Debug, Clone, PartialEq)]
pub struct AccessibilityNode {
    /// Stable widget identity.
    pub id: WidgetId,
    /// Parent node ID, if the node is nested in another semantic node.
    pub parent: Option<WidgetId>,
    /// Semantic role.
    pub role: SemanticRole,
    /// Logical bounds.
    pub bounds: Rect,
    /// Accessible name.
    pub label: Option<String>,
    /// Longer accessible description.
    pub description: Option<String>,
    /// Runtime state.
    pub state: SemanticState,
    /// Supported semantic actions.
    pub actions: Vec<SemanticAction>,
    /// Ordered child node IDs.
    pub children: Vec<WidgetId>,
    /// Whether the node participates in focus traversal.
    pub focusable: bool,
}

impl AccessibilityNode {
    fn from_semantic(node: &SemanticNode, parent: Option<WidgetId>) -> Self {
        Self {
            id: node.id,
            parent,
            role: node.role.clone(),
            bounds: node.bounds,
            label: node.label.clone(),
            description: node.description.clone(),
            state: node.state.clone(),
            actions: node.actions.clone(),
            children: node.children.clone(),
            focusable: node.focusable,
        }
    }
}

/// Validated accessibility snapshot exported for platform adapters.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct AccessibilitySnapshot {
    /// Root node ID, if the frame emitted semantic content.
    pub root: Option<WidgetId>,
    /// Nodes in deterministic semantic traversal order.
    pub nodes: Vec<AccessibilityNode>,
    /// Focusable nodes in deterministic traversal order.
    pub focus_order: Vec<WidgetId>,
    /// Focused widget when it is present in `focus_order`.
    pub focused: Option<WidgetId>,
}

impl AccessibilitySnapshot {
    /// Builds a snapshot from a semantic tree after validating structure.
    ///
    /// # Errors
    ///
    /// Returns [`SemanticTreeError`] when the semantic tree is structurally
    /// invalid.
    pub fn from_tree(
        tree: &SemanticTree,
        focused: Option<WidgetId>,
    ) -> Result<Self, SemanticTreeError> {
        tree.validate()?;

        let focus = FocusTraversal::from_tree(tree, focused);
        let nodes = tree
            .traversal_order()
            .into_iter()
            .filter_map(|id| {
                tree.get(id)
                    .map(|node| AccessibilityNode::from_semantic(node, tree.parent_of(id)))
            })
            .collect();

        Ok(Self {
            root: tree.root(),
            nodes,
            focus_order: focus.order,
            focused: focus.focused,
        })
    }

    /// Finds an exported node by ID.
    #[must_use]
    pub fn node(&self, id: WidgetId) -> Option<&AccessibilityNode> {
        self.nodes.iter().find(|node| node.id == id)
    }

    /// Finds an exported node by semantic widget ID.
    #[must_use]
    pub fn find_by_id(&self, id: WidgetId) -> Option<&AccessibilityNode> {
        self.node(id)
    }

    /// Returns exported nodes with the requested semantic role.
    pub fn nodes_by_role<'a>(
        &'a self,
        role: &'a SemanticRole,
    ) -> impl Iterator<Item = &'a AccessibilityNode> + 'a {
        self.nodes.iter().filter(move |node| &node.role == role)
    }

    /// Returns exported nodes with the requested exact accessible label.
    pub fn nodes_by_label<'a>(
        &'a self,
        label: &'a str,
    ) -> impl Iterator<Item = &'a AccessibilityNode> + 'a {
        self.nodes
            .iter()
            .filter(move |node| node.label.as_deref() == Some(label))
    }

    /// Finds the first exported node with the requested exact accessible label.
    #[must_use]
    pub fn find_by_label(&self, label: &str) -> Option<&AccessibilityNode> {
        self.nodes
            .iter()
            .find(|node| node.label.as_deref() == Some(label))
    }

    /// Returns exported nodes with both the requested role and exact label.
    pub fn nodes_by_role_and_label<'a>(
        &'a self,
        role: &'a SemanticRole,
        label: &'a str,
    ) -> impl Iterator<Item = &'a AccessibilityNode> + 'a {
        self.nodes
            .iter()
            .filter(move |node| &node.role == role && node.label.as_deref() == Some(label))
    }

    /// Finds the first exported node with both the requested role and exact label.
    #[must_use]
    pub fn find_by_role_and_label(
        &self,
        role: &SemanticRole,
        label: &str,
    ) -> Option<&AccessibilityNode> {
        self.nodes
            .iter()
            .find(|node| &node.role == role && node.label.as_deref() == Some(label))
    }

    /// Returns exported nodes with the requested semantic value.
    pub fn nodes_by_value<'a>(
        &'a self,
        value: &'a SemanticValue,
    ) -> impl Iterator<Item = &'a AccessibilityNode> + 'a {
        self.nodes
            .iter()
            .filter(move |node| node.state.value.as_ref() == Some(value))
    }

    /// Finds the first exported node with the requested semantic value.
    #[must_use]
    pub fn find_by_value(&self, value: &SemanticValue) -> Option<&AccessibilityNode> {
        self.nodes
            .iter()
            .find(|node| node.state.value.as_ref() == Some(value))
    }

    /// Returns exported nodes that support the requested semantic action kind.
    pub fn nodes_by_action<'a>(
        &'a self,
        action: &'a SemanticActionKind,
    ) -> impl Iterator<Item = &'a AccessibilityNode> + 'a {
        self.nodes.iter().filter(move |node| {
            node.actions
                .iter()
                .any(|candidate| &candidate.kind == action)
        })
    }

    /// Finds the first exported node that supports the requested semantic action kind.
    #[must_use]
    pub fn find_by_action(&self, action: &SemanticActionKind) -> Option<&AccessibilityNode> {
        self.nodes.iter().find(|node| {
            node.actions
                .iter()
                .any(|candidate| &candidate.kind == action)
        })
    }

    /// Returns exported nodes whose semantic state matches the predicate.
    pub fn nodes_by_state<'a>(
        &'a self,
        mut predicate: impl FnMut(&SemanticState) -> bool + 'a,
    ) -> impl Iterator<Item = &'a AccessibilityNode> + 'a {
        self.nodes.iter().filter(move |node| predicate(&node.state))
    }

    /// Finds the first exported node whose semantic state matches the predicate.
    #[must_use]
    pub fn find_by_state(
        &self,
        mut predicate: impl FnMut(&SemanticState) -> bool,
    ) -> Option<&AccessibilityNode> {
        self.nodes.iter().find(|node| predicate(&node.state))
    }

    /// Returns focusable exported nodes in deterministic focus traversal order.
    pub fn focus_order_nodes(&self) -> impl Iterator<Item = &AccessibilityNode> {
        self.focus_order.iter().filter_map(|id| self.node(*id))
    }
}

fn validate_semantic_cycles(
    id: WidgetId,
    children_by_parent: &BTreeMap<WidgetId, Vec<WidgetId>>,
    visiting: &mut BTreeSet<WidgetId>,
    visited: &mut BTreeSet<WidgetId>,
) -> Result<(), SemanticTreeError> {
    if visited.contains(&id) {
        return Ok(());
    }
    if !visiting.insert(id) {
        return Err(SemanticTreeError::Cycle { id });
    }
    if let Some(children) = children_by_parent.get(&id) {
        for child in children {
            validate_semantic_cycles(*child, children_by_parent, visiting, visited)?;
        }
    }
    visiting.remove(&id);
    visited.insert(id);
    Ok(())
}

/// Deterministic focus traversal snapshot.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FocusTraversal {
    /// Focusable widgets in traversal order.
    pub order: Vec<WidgetId>,
    /// Currently focused widget.
    pub focused: Option<WidgetId>,
}

impl FocusTraversal {
    /// Creates traversal from a semantic tree.
    #[must_use]
    pub fn from_tree(tree: &SemanticTree, focused: Option<WidgetId>) -> Self {
        let order = tree.focus_order();
        let focused = focused.filter(|id| order.contains(id));
        Self { order, focused }
    }

    /// Returns the next focus target, wrapping at the end.
    #[must_use]
    pub fn next(&self) -> Option<WidgetId> {
        cycle_focus(&self.order, self.focused, FocusDirection::Forward)
    }

    /// Returns the previous focus target, wrapping at the start.
    #[must_use]
    pub fn previous(&self) -> Option<WidgetId> {
        cycle_focus(&self.order, self.focused, FocusDirection::Backward)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum FocusDirection {
    Forward,
    Backward,
}

fn cycle_focus(
    order: &[WidgetId],
    focused: Option<WidgetId>,
    direction: FocusDirection,
) -> Option<WidgetId> {
    if order.is_empty() {
        return None;
    }
    let index = focused
        .and_then(|id| order.iter().position(|candidate| *candidate == id))
        .unwrap_or_else(|| match direction {
            FocusDirection::Forward => order.len() - 1,
            FocusDirection::Backward => 0,
        });
    let next = match direction {
        FocusDirection::Forward => (index + 1) % order.len(),
        FocusDirection::Backward => (index + order.len() - 1) % order.len(),
    };
    Some(order[next])
}

/// Boundary implemented by platform-specific accessibility adapters.
pub trait AccessibilityAdapter {
    /// Adapter error type.
    type Error;

    /// Synchronizes the platform accessibility tree with the current snapshot.
    ///
    /// # Errors
    ///
    /// Returns an adapter-specific error when platform synchronization fails.
    fn synchronize(&mut self, snapshot: &AccessibilitySnapshot) -> Result<(), Self::Error>;

    /// Notifies the platform that focus moved.
    ///
    /// # Errors
    ///
    /// Returns an adapter-specific error when the platform focus update fails.
    fn focus(&mut self, node: WidgetId) -> Result<(), Self::Error>;

    /// Requests a semantic action on a node.
    ///
    /// # Errors
    ///
    /// Returns an adapter-specific error when the platform cannot perform the action.
    fn perform_action(
        &mut self,
        node: WidgetId,
        action: &SemanticActionKind,
    ) -> Result<(), Self::Error>;
}

#[cfg(test)]
mod tests {
    use std::convert::Infallible;

    use super::{
        AccessibilityAdapter, AccessibilitySnapshot, FocusTraversal, SemanticAction,
        SemanticActionKind, SemanticNode, SemanticRole, SemanticState, SemanticTree,
        SemanticTreeError, SemanticValue,
    };
    use crate::{ActionDescriptor, Rect, WidgetId};

    #[derive(Debug, Default)]
    struct RecordingAdapter {
        synchronized: Vec<AccessibilitySnapshot>,
        focused: Vec<WidgetId>,
        actions: Vec<(WidgetId, SemanticActionKind)>,
    }

    impl AccessibilityAdapter for RecordingAdapter {
        type Error = Infallible;

        fn synchronize(&mut self, snapshot: &AccessibilitySnapshot) -> Result<(), Self::Error> {
            self.synchronized.push(snapshot.clone());
            Ok(())
        }

        fn focus(&mut self, node: WidgetId) -> Result<(), Self::Error> {
            self.focused.push(node);
            Ok(())
        }

        fn perform_action(
            &mut self,
            node: WidgetId,
            action: &SemanticActionKind,
        ) -> Result<(), Self::Error> {
            self.actions.push((node, action.clone()));
            Ok(())
        }
    }

    #[test]
    fn semantic_tree_preserves_nodes_and_focus_order() {
        let root = WidgetId::from_key("root");
        let disabled = WidgetId::from_key("disabled");
        let button = WidgetId::from_key("button");
        let mut tree = SemanticTree::new();
        tree.push(SemanticNode::new(root, SemanticRole::Root, Rect::ZERO));
        tree.push(
            SemanticNode::new(disabled, SemanticRole::Button, Rect::ZERO)
                .focusable(true)
                .with_label("Disabled"),
        );
        tree.nodes[1].state.disabled = true;
        tree.push(SemanticNode::new(button, SemanticRole::Button, Rect::ZERO).focusable(true));

        assert_eq!(tree.root(), Some(root));
        assert_eq!(
            tree.get(button).map(|node| &node.role),
            Some(&SemanticRole::Button)
        );
        assert_eq!(tree.focus_order(), vec![button]);
    }

    #[test]
    fn focus_traversal_wraps_in_both_directions() {
        let first = WidgetId::from_key("first");
        let second = WidgetId::from_key("second");
        let traversal = FocusTraversal {
            order: vec![first, second],
            focused: Some(second),
        };

        assert_eq!(traversal.next(), Some(first));
        assert_eq!(traversal.previous(), Some(first));
    }

    #[test]
    fn action_descriptor_maps_to_semantic_invoke_action() {
        let descriptor = ActionDescriptor::new("file.save", "Save");
        let action = SemanticAction::from_action_descriptor(&descriptor);

        assert_eq!(action.kind, SemanticActionKind::Invoke);
        assert_eq!(action.label, "Save");
        assert_eq!(action.action_id, Some(descriptor.id));
    }

    #[test]
    fn semantic_state_tracks_roles_values_and_actions() {
        let id = WidgetId::from_key("slider");
        let node = SemanticNode::new(id, SemanticRole::Slider, Rect::new(0.0, 0.0, 100.0, 16.0))
            .focusable(true)
            .with_action(SemanticAction::new(
                SemanticActionKind::Increment,
                "Increase",
            ));

        let mut state = SemanticState {
            value: Some(SemanticValue::Number {
                current: 0.5,
                min: 0.0,
                max: 1.0,
            }),
            ..SemanticState::default()
        };
        state.checked = Some(false);

        assert!(node.focusable);
        assert!(
            node.actions
                .iter()
                .any(|action| action.kind == SemanticActionKind::Focus)
        );
        assert_eq!(state.checked, Some(false));
    }

    #[test]
    fn semantic_tree_traversal_uses_declared_child_order() {
        let root = WidgetId::from_key("root");
        let first = WidgetId::from_key("first");
        let second = WidgetId::from_key("second");
        let mut tree = SemanticTree::new();
        tree.push(
            SemanticNode::new(root, SemanticRole::Root, Rect::ZERO).with_children([second, first]),
        );
        tree.push(SemanticNode::new(first, SemanticRole::Button, Rect::ZERO).focusable(true));
        tree.push(SemanticNode::new(second, SemanticRole::Button, Rect::ZERO).focusable(true));

        assert_eq!(tree.traversal_order(), vec![root, second, first]);
        assert_eq!(tree.focus_order(), vec![second, first]);
        assert_eq!(tree.parent_of(first), Some(root));
        assert!(tree.validate().is_ok());
    }

    #[test]
    fn accessibility_snapshot_exports_validated_semantics_in_traversal_order() {
        let root = WidgetId::from_key("root");
        let button = WidgetId::from_key("button");
        let slider = WidgetId::from_key("slider");
        let unparented = WidgetId::from_key("unparented");
        let mut tree = SemanticTree::new();
        tree.push(
            SemanticNode::new(root, SemanticRole::Root, Rect::ZERO).with_children([slider, button]),
        );
        tree.push(
            SemanticNode::new(
                button,
                SemanticRole::Button,
                Rect::new(0.0, 0.0, 80.0, 28.0),
            )
            .focusable(true)
            .with_label("Run")
            .with_action(SemanticAction::new(SemanticActionKind::Invoke, "Run")),
        );
        let mut slider_node = SemanticNode::new(
            slider,
            SemanticRole::Slider,
            Rect::new(0.0, 32.0, 120.0, 18.0),
        )
        .focusable(true)
        .with_label("Opacity")
        .with_action(SemanticAction::new(
            SemanticActionKind::Increment,
            "Increase",
        ));
        slider_node.state.value = Some(SemanticValue::Number {
            current: 0.5,
            min: 0.0,
            max: 1.0,
        });
        tree.push(slider_node);
        tree.push(SemanticNode::new(
            unparented,
            SemanticRole::Label,
            Rect::new(0.0, 56.0, 100.0, 18.0),
        ));

        let snapshot = tree.accessibility_snapshot(Some(button)).expect("snapshot");

        assert_eq!(snapshot.root, Some(root));
        assert_eq!(
            snapshot
                .nodes
                .iter()
                .map(|node| node.id)
                .collect::<Vec<_>>(),
            vec![root, slider, button, unparented]
        );
        assert_eq!(snapshot.focus_order, vec![slider, button]);
        assert_eq!(snapshot.focused, Some(button));
        assert_eq!(snapshot.node(slider).expect("slider").parent, Some(root));
        assert_eq!(
            snapshot.node(button).expect("button").label.as_deref(),
            Some("Run")
        );
        assert_eq!(
            snapshot.node(slider).expect("slider").state.value,
            Some(SemanticValue::Number {
                current: 0.5,
                min: 0.0,
                max: 1.0,
            })
        );
        assert!(
            snapshot
                .node(slider)
                .expect("slider")
                .actions
                .iter()
                .any(|action| action.kind == SemanticActionKind::Increment)
        );
    }

    #[test]
    fn accessibility_snapshot_rejects_invalid_semantic_trees() {
        let root = WidgetId::from_key("root");
        let missing = WidgetId::from_key("missing");
        let mut tree = SemanticTree::new();
        tree.push(SemanticNode::new(root, SemanticRole::Root, Rect::ZERO).with_children([missing]));

        assert_eq!(
            tree.accessibility_snapshot(None).expect_err("error"),
            SemanticTreeError::UnknownChild {
                parent: root,
                child: missing,
            }
        );
    }

    #[test]
    fn accessibility_adapter_synchronizes_snapshots_and_actions() {
        let root = WidgetId::from_key("root");
        let button = WidgetId::from_key("button");
        let mut tree = SemanticTree::new();
        tree.push(SemanticNode::new(root, SemanticRole::Root, Rect::ZERO).with_children([button]));
        tree.push(SemanticNode::new(button, SemanticRole::Button, Rect::ZERO).focusable(true));
        let snapshot = tree.accessibility_snapshot(Some(button)).expect("snapshot");
        let mut adapter = RecordingAdapter::default();

        adapter.synchronize(&snapshot).expect("sync");
        adapter.focus(button).expect("focus");
        adapter
            .perform_action(button, &SemanticActionKind::Invoke)
            .expect("action");

        assert_eq!(adapter.synchronized, vec![snapshot]);
        assert_eq!(adapter.focused, vec![button]);
        assert_eq!(adapter.actions, vec![(button, SemanticActionKind::Invoke)]);
    }

    #[test]
    fn semantic_tree_validation_accepts_empty_trees() {
        let tree = SemanticTree::new();

        assert!(tree.is_empty());
        assert_eq!(tree.len(), 0);
        assert!(tree.validate().is_ok());
    }

    #[test]
    fn semantic_tree_validation_rejects_bad_roots_and_duplicate_nodes() {
        let root = WidgetId::from_key("root");
        let missing = WidgetId::from_key("missing");
        let mut unknown_root = SemanticTree::new();
        unknown_root.push(SemanticNode::new(root, SemanticRole::Root, Rect::ZERO));
        unknown_root.set_root(missing);

        assert_eq!(
            unknown_root.validate().expect_err("error"),
            SemanticTreeError::UnknownRoot { id: missing }
        );

        let mut missing_root = SemanticTree {
            nodes: vec![SemanticNode::new(root, SemanticRole::Root, Rect::ZERO)],
            root: None,
        };
        assert_eq!(
            missing_root.validate().expect_err("error"),
            SemanticTreeError::MissingRoot
        );

        missing_root.root = Some(root);
        missing_root
            .nodes
            .push(SemanticNode::new(root, SemanticRole::Panel, Rect::ZERO));
        assert_eq!(
            missing_root.validate().expect_err("error"),
            SemanticTreeError::DuplicateNodeId { id: root }
        );
    }

    #[test]
    fn semantic_tree_validation_rejects_bad_child_edges() {
        let root = WidgetId::from_key("root");
        let child = WidgetId::from_key("child");
        let missing = WidgetId::from_key("missing");

        let mut unknown_child = SemanticTree::new();
        unknown_child
            .push(SemanticNode::new(root, SemanticRole::Root, Rect::ZERO).with_children([missing]));
        assert_eq!(
            unknown_child.validate().expect_err("error"),
            SemanticTreeError::UnknownChild {
                parent: root,
                child: missing
            }
        );

        let mut duplicate_child = SemanticTree::new();
        duplicate_child.push(
            SemanticNode::new(root, SemanticRole::Root, Rect::ZERO).with_children([child, child]),
        );
        duplicate_child.push(SemanticNode::new(child, SemanticRole::Button, Rect::ZERO));
        assert_eq!(
            duplicate_child.validate().expect_err("error"),
            SemanticTreeError::DuplicateChild {
                parent: root,
                child
            }
        );

        let mut self_child = SemanticTree::new();
        self_child
            .push(SemanticNode::new(root, SemanticRole::Root, Rect::ZERO).with_children([root]));
        assert_eq!(
            self_child.validate().expect_err("error"),
            SemanticTreeError::SelfChild { id: root }
        );
    }

    #[test]
    fn semantic_tree_validation_rejects_ambiguous_parentage_and_cycles() {
        let root = WidgetId::from_key("root");
        let other = WidgetId::from_key("other");
        let child = WidgetId::from_key("child");

        let mut multiple_parents = SemanticTree::new();
        multiple_parents
            .push(SemanticNode::new(root, SemanticRole::Root, Rect::ZERO).with_children([child]));
        multiple_parents
            .push(SemanticNode::new(other, SemanticRole::Panel, Rect::ZERO).with_children([child]));
        multiple_parents.push(SemanticNode::new(child, SemanticRole::Button, Rect::ZERO));
        assert_eq!(
            multiple_parents.validate().expect_err("error"),
            SemanticTreeError::MultipleParents {
                child,
                first_parent: root,
                second_parent: other
            }
        );

        let mut cycle = SemanticTree::new();
        cycle.push(SemanticNode::new(root, SemanticRole::Root, Rect::ZERO).with_children([child]));
        cycle.push(SemanticNode::new(child, SemanticRole::Panel, Rect::ZERO).with_children([root]));
        assert_eq!(
            cycle.validate().expect_err("error"),
            SemanticTreeError::Cycle { id: root }
        );
    }
}
