//! Platform-independent accessibility semantics.

use crate::{ActionDescriptor, ActionId, Rect, WidgetId};

/// Semantic role exposed by a UI node.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum SemanticRole {
    /// Application or document root.
    Root,
    /// Dock area that owns frames.
    DockArea,
    /// Docked frame container.
    Frame,
    /// Passive panel or inspector region.
    Panel,
    /// Static label text.
    Label,
    /// Push button.
    Button,
    /// Icon-only button.
    IconButton,
    /// Checkbox control.
    CheckBox,
    /// Radio button control.
    RadioButton,
    /// Toggle/switch control.
    Toggle,
    /// Slider control.
    Slider,
    /// Single-line or multi-line text field.
    TextField,
    /// Search field.
    SearchField,
    /// Static image.
    Image,
    /// Virtual or concrete list.
    List,
    /// List item.
    ListItem,
    /// Grid collection.
    Grid,
    /// Data table.
    Table,
    /// Table row.
    Row,
    /// Table cell.
    Cell,
    /// Tab list.
    TabList,
    /// Tab header.
    Tab,
    /// Menu surface.
    Menu,
    /// Menu item.
    MenuItem,
    /// Command palette surface.
    CommandPalette,
    /// Media, video, image, or 3D viewport.
    Viewport,
    /// Application-defined role.
    Custom(String),
}

/// Value attached to semantic controls such as sliders and text fields.
#[derive(Debug, Clone, PartialEq)]
pub enum SemanticValue {
    /// Text value.
    Text(String),
    /// Numeric value with inclusive bounds.
    Number {
        /// Current value.
        current: f32,
        /// Minimum allowed value.
        min: f32,
        /// Maximum allowed value.
        max: f32,
    },
}

/// Runtime semantic state for a node.
#[derive(Debug, Clone, Default, PartialEq)]
#[allow(clippy::struct_excessive_bools)]
pub struct SemanticState {
    /// Node cannot currently be operated.
    pub disabled: bool,
    /// Node owns keyboard focus.
    pub focused: bool,
    /// Node is selected.
    pub selected: bool,
    /// Node is checked, when the role supports checked state.
    pub checked: Option<bool>,
    /// Node is expanded, when the role supports disclosure state.
    pub expanded: Option<bool>,
    /// Node is actively pressed.
    pub pressed: bool,
    /// Node value.
    pub value: Option<SemanticValue>,
}

/// Accessibility action kind supported by a semantic node.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum SemanticActionKind {
    /// Invoke the default action.
    Invoke,
    /// Move keyboard focus to the node.
    Focus,
    /// Increment a value.
    Increment,
    /// Decrement a value.
    Decrement,
    /// Set a numeric value.
    SetValue,
    /// Set text content.
    SetText,
    /// Open a popup or disclosure.
    Open,
    /// Close a popup or disclosure.
    Close,
    /// Dismiss an overlay.
    Dismiss,
    /// Application-defined action.
    Custom(String),
}

/// Semantic action exposed on a node.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SemanticAction {
    /// Action kind.
    pub kind: SemanticActionKind,
    /// Human-readable action label.
    pub label: String,
    /// Optional application action identity.
    pub action_id: Option<ActionId>,
}

impl SemanticAction {
    /// Creates a semantic action.
    #[must_use]
    pub fn new(kind: SemanticActionKind, label: impl Into<String>) -> Self {
        Self {
            kind,
            label: label.into(),
            action_id: None,
        }
    }

    /// Creates an invoke action from an application action descriptor.
    #[must_use]
    pub fn from_action_descriptor(descriptor: &ActionDescriptor) -> Self {
        Self {
            kind: SemanticActionKind::Invoke,
            label: descriptor.label.clone(),
            action_id: Some(descriptor.id.clone()),
        }
    }
}

/// Semantic node generated by UI code.
#[derive(Debug, Clone, PartialEq)]
pub struct SemanticNode {
    /// Stable widget identity.
    pub id: WidgetId,
    /// Semantic role.
    pub role: SemanticRole,
    /// Logical bounds.
    pub bounds: Rect,
    /// Accessible name.
    pub label: Option<String>,
    /// Longer accessible description.
    pub description: Option<String>,
    /// Runtime state.
    pub state: SemanticState,
    /// Supported semantic actions.
    pub actions: Vec<SemanticAction>,
    /// Ordered child node IDs.
    pub children: Vec<WidgetId>,
    /// Whether the node participates in focus traversal.
    pub focusable: bool,
}

impl SemanticNode {
    /// Creates a semantic node.
    #[must_use]
    pub fn new(id: WidgetId, role: SemanticRole, bounds: Rect) -> Self {
        Self {
            id,
            role,
            bounds,
            label: None,
            description: None,
            state: SemanticState::default(),
            actions: Vec::new(),
            children: Vec::new(),
            focusable: false,
        }
    }

    /// Assigns an accessible label.
    #[must_use]
    pub fn with_label(mut self, label: impl Into<String>) -> Self {
        self.label = Some(label.into());
        self
    }

    /// Marks the node as focusable and adds a focus action.
    #[must_use]
    pub fn focusable(mut self, focusable: bool) -> Self {
        self.focusable = focusable;
        if focusable
            && !self
                .actions
                .iter()
                .any(|action| action.kind == SemanticActionKind::Focus)
        {
            self.actions
                .push(SemanticAction::new(SemanticActionKind::Focus, "Focus"));
        }
        self
    }

    /// Adds a supported action.
    #[must_use]
    pub fn with_action(mut self, action: SemanticAction) -> Self {
        self.actions.push(action);
        self
    }

    /// Adds child node IDs in visual order.
    #[must_use]
    pub fn with_children(mut self, children: impl IntoIterator<Item = WidgetId>) -> Self {
        self.children.extend(children);
        self
    }
}

/// Semantic tree for one UI frame.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct SemanticTree {
    nodes: Vec<SemanticNode>,
    root: Option<WidgetId>,
}

impl SemanticTree {
    /// Creates an empty semantic tree.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Sets the root node ID.
    pub fn set_root(&mut self, root: WidgetId) {
        self.root = Some(root);
    }

    /// Returns the root node ID.
    #[must_use]
    pub const fn root(&self) -> Option<WidgetId> {
        self.root
    }

    /// Pushes a node in traversal order.
    pub fn push(&mut self, node: SemanticNode) {
        if self.root.is_none() {
            self.root = Some(node.id);
        }
        self.nodes.push(node);
    }

    /// Returns all nodes in insertion order.
    #[must_use]
    pub fn nodes(&self) -> &[SemanticNode] {
        &self.nodes
    }

    /// Finds a node by ID.
    #[must_use]
    pub fn get(&self, id: WidgetId) -> Option<&SemanticNode> {
        self.nodes.iter().find(|node| node.id == id)
    }

    /// Returns focusable node IDs in traversal order.
    #[must_use]
    pub fn focus_order(&self) -> Vec<WidgetId> {
        self.nodes
            .iter()
            .filter(|node| node.focusable && !node.state.disabled)
            .map(|node| node.id)
            .collect()
    }
}

/// Deterministic focus traversal snapshot.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FocusTraversal {
    /// Focusable widgets in traversal order.
    pub order: Vec<WidgetId>,
    /// Currently focused widget.
    pub focused: Option<WidgetId>,
}

impl FocusTraversal {
    /// Creates traversal from a semantic tree.
    #[must_use]
    pub fn from_tree(tree: &SemanticTree, focused: Option<WidgetId>) -> Self {
        let order = tree.focus_order();
        let focused = focused.filter(|id| order.contains(id));
        Self { order, focused }
    }

    /// Returns the next focus target, wrapping at the end.
    #[must_use]
    pub fn next(&self) -> Option<WidgetId> {
        cycle_focus(&self.order, self.focused, FocusDirection::Forward)
    }

    /// Returns the previous focus target, wrapping at the start.
    #[must_use]
    pub fn previous(&self) -> Option<WidgetId> {
        cycle_focus(&self.order, self.focused, FocusDirection::Backward)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum FocusDirection {
    Forward,
    Backward,
}

fn cycle_focus(
    order: &[WidgetId],
    focused: Option<WidgetId>,
    direction: FocusDirection,
) -> Option<WidgetId> {
    if order.is_empty() {
        return None;
    }
    let index = focused
        .and_then(|id| order.iter().position(|candidate| *candidate == id))
        .unwrap_or_else(|| match direction {
            FocusDirection::Forward => order.len() - 1,
            FocusDirection::Backward => 0,
        });
    let next = match direction {
        FocusDirection::Forward => (index + 1) % order.len(),
        FocusDirection::Backward => (index + order.len() - 1) % order.len(),
    };
    Some(order[next])
}

/// Boundary implemented by platform-specific accessibility adapters.
pub trait AccessibilityAdapter {
    /// Adapter error type.
    type Error;

    /// Synchronizes the platform accessibility tree with the current semantic tree.
    ///
    /// # Errors
    ///
    /// Returns an adapter-specific error when platform synchronization fails.
    fn synchronize(&mut self, tree: &SemanticTree) -> Result<(), Self::Error>;

    /// Notifies the platform that focus moved.
    ///
    /// # Errors
    ///
    /// Returns an adapter-specific error when the platform focus update fails.
    fn focus(&mut self, node: WidgetId) -> Result<(), Self::Error>;

    /// Requests a semantic action on a node.
    ///
    /// # Errors
    ///
    /// Returns an adapter-specific error when the platform cannot perform the action.
    fn perform_action(
        &mut self,
        node: WidgetId,
        action: &SemanticActionKind,
    ) -> Result<(), Self::Error>;
}

#[cfg(test)]
mod tests {
    use super::{
        FocusTraversal, SemanticAction, SemanticActionKind, SemanticNode, SemanticRole,
        SemanticState, SemanticTree, SemanticValue,
    };
    use crate::{ActionDescriptor, Rect, WidgetId};

    #[test]
    fn semantic_tree_preserves_nodes_and_focus_order() {
        let root = WidgetId::from_key("root");
        let disabled = WidgetId::from_key("disabled");
        let button = WidgetId::from_key("button");
        let mut tree = SemanticTree::new();
        tree.push(SemanticNode::new(root, SemanticRole::Root, Rect::ZERO));
        tree.push(
            SemanticNode::new(disabled, SemanticRole::Button, Rect::ZERO)
                .focusable(true)
                .with_label("Disabled"),
        );
        tree.nodes[1].state.disabled = true;
        tree.push(SemanticNode::new(button, SemanticRole::Button, Rect::ZERO).focusable(true));

        assert_eq!(tree.root(), Some(root));
        assert_eq!(
            tree.get(button).map(|node| &node.role),
            Some(&SemanticRole::Button)
        );
        assert_eq!(tree.focus_order(), vec![button]);
    }

    #[test]
    fn focus_traversal_wraps_in_both_directions() {
        let first = WidgetId::from_key("first");
        let second = WidgetId::from_key("second");
        let traversal = FocusTraversal {
            order: vec![first, second],
            focused: Some(second),
        };

        assert_eq!(traversal.next(), Some(first));
        assert_eq!(traversal.previous(), Some(first));
    }

    #[test]
    fn action_descriptor_maps_to_semantic_invoke_action() {
        let descriptor = ActionDescriptor::new("file.save", "Save");
        let action = SemanticAction::from_action_descriptor(&descriptor);

        assert_eq!(action.kind, SemanticActionKind::Invoke);
        assert_eq!(action.label, "Save");
        assert_eq!(action.action_id, Some(descriptor.id));
    }

    #[test]
    fn semantic_state_tracks_roles_values_and_actions() {
        let id = WidgetId::from_key("slider");
        let node = SemanticNode::new(id, SemanticRole::Slider, Rect::new(0.0, 0.0, 100.0, 16.0))
            .focusable(true)
            .with_action(SemanticAction::new(
                SemanticActionKind::Increment,
                "Increase",
            ));

        let mut state = SemanticState {
            value: Some(SemanticValue::Number {
                current: 0.5,
                min: 0.0,
                max: 1.0,
            }),
            ..SemanticState::default()
        };
        state.checked = Some(false);

        assert!(node.focusable);
        assert!(
            node.actions
                .iter()
                .any(|action| action.kind == SemanticActionKind::Focus)
        );
        assert_eq!(state.checked, Some(false));
    }
}
