use crate::{ActionDescriptor, ActionId, Rect, WidgetId};

/// Semantic role exposed by a UI node.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum SemanticRole {
    /// Application or document root.
    Root,
    /// Dock that owns frames.
    Dock,
    /// Docked frame container.
    Frame,
    /// Passive panel or inspector region.
    Panel,
    /// Static label text.
    Label,
    /// Push button.
    Button,
    /// Icon-only button.
    IconButton,
    /// Checkbox control.
    CheckBox,
    /// Radio button control.
    RadioButton,
    /// Toggle/switch control.
    Toggle,
    /// Slider control.
    Slider,
    /// Single-line or multi-line text field.
    TextField,
    /// Search field.
    SearchField,
    /// Static image.
    Image,
    /// Virtual or concrete list.
    List,
    /// List item.
    ListItem,
    /// Grid collection.
    Grid,
    /// Data table.
    Table,
    /// Table row.
    Row,
    /// Table cell.
    Cell,
    /// Tab list.
    TabList,
    /// Tab header.
    Tab,
    /// Menu surface.
    Menu,
    /// Menu item.
    MenuItem,
    /// Command palette surface.
    CommandPalette,
    /// Media, video, image, or 3D viewport.
    Viewport,
    /// Application-defined role.
    Custom(String),
}

/// Value attached to semantic controls such as sliders and text fields.
#[derive(Debug, Clone, PartialEq)]
pub enum SemanticValue {
    /// Text value.
    Text(String),
    /// Numeric value with inclusive bounds.
    Number {
        /// Current value.
        current: f32,
        /// Minimum allowed value.
        min: f32,
        /// Maximum allowed value.
        max: f32,
    },
}

/// Runtime semantic state for a node.
#[derive(Debug, Clone, Default, PartialEq)]
#[allow(clippy::struct_excessive_bools)]
pub struct SemanticState {
    /// Node cannot currently be operated.
    pub disabled: bool,
    /// Node owns keyboard focus.
    pub focused: bool,
    /// Node is selected.
    pub selected: bool,
    /// Node is checked, when the role supports checked state.
    pub checked: Option<bool>,
    /// Node is expanded, when the role supports disclosure state.
    pub expanded: Option<bool>,
    /// Node is actively pressed.
    pub pressed: bool,
    /// Node value.
    pub value: Option<SemanticValue>,
}

/// Accessibility action kind supported by a semantic node.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum SemanticActionKind {
    /// Invoke the default action.
    Invoke,
    /// Move keyboard focus to the node.
    Focus,
    /// Increment a value.
    Increment,
    /// Decrement a value.
    Decrement,
    /// Set a numeric value.
    SetValue,
    /// Set text content.
    SetText,
    /// Open a popup or disclosure.
    Open,
    /// Close a popup or disclosure.
    Close,
    /// Dismiss an overlay.
    Dismiss,
    /// Application-defined action.
    Custom(String),
}

/// Semantic action exposed on a node.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SemanticAction {
    /// Action kind.
    pub kind: SemanticActionKind,
    /// Human-readable action label.
    pub label: String,
    /// Optional application action identity.
    pub action_id: Option<ActionId>,
}

impl SemanticAction {
    /// Creates a semantic action.
    #[must_use]
    pub fn new(kind: SemanticActionKind, label: impl Into<String>) -> Self {
        Self {
            kind,
            label: label.into(),
            action_id: None,
        }
    }

    /// Creates an invoke action from an application action descriptor.
    #[must_use]
    pub fn from_action_descriptor(descriptor: &ActionDescriptor) -> Self {
        Self {
            kind: SemanticActionKind::Invoke,
            label: descriptor.label.clone(),
            action_id: Some(descriptor.id.clone()),
        }
    }
}

/// Semantic node generated by UI code.
#[derive(Debug, Clone, PartialEq)]
pub struct SemanticNode {
    /// Stable widget identity.
    pub id: WidgetId,
    /// Semantic role.
    pub role: SemanticRole,
    /// Logical bounds.
    pub bounds: Rect,
    /// Accessible name.
    pub label: Option<String>,
    /// Longer accessible description.
    pub description: Option<String>,
    /// Runtime state.
    pub state: SemanticState,
    /// Supported semantic actions.
    pub actions: Vec<SemanticAction>,
    /// Ordered child node IDs.
    pub children: Vec<WidgetId>,
    /// Whether the node participates in focus traversal.
    pub focusable: bool,
}

impl SemanticNode {
    /// Creates a semantic node.
    #[must_use]
    pub fn new(id: WidgetId, role: SemanticRole, bounds: Rect) -> Self {
        Self {
            id,
            role,
            bounds,
            label: None,
            description: None,
            state: SemanticState::default(),
            actions: Vec::new(),
            children: Vec::new(),
            focusable: false,
        }
    }

    /// Assigns an accessible label.
    #[must_use]
    pub fn with_label(mut self, label: impl Into<String>) -> Self {
        self.label = Some(label.into());
        self
    }

    /// Marks the node as focusable and adds a focus action.
    #[must_use]
    pub fn focusable(mut self, focusable: bool) -> Self {
        self.focusable = focusable;
        if focusable
            && !self
                .actions
                .iter()
                .any(|action| action.kind == SemanticActionKind::Focus)
        {
            self.actions
                .push(SemanticAction::new(SemanticActionKind::Focus, "Focus"));
        }
        self
    }

    /// Adds a supported action.
    #[must_use]
    pub fn with_action(mut self, action: SemanticAction) -> Self {
        self.actions.push(action);
        self
    }

    /// Adds child node IDs in visual order.
    #[must_use]
    pub fn with_children(mut self, children: impl IntoIterator<Item = WidgetId>) -> Self {
        self.children.extend(children);
        self
    }
}
