//! Deterministic Rust source generation and drift checking.

use std::{
    collections::{BTreeMap, BTreeSet},
    fmt::Write as _,
    fs, io,
    path::{Path, PathBuf},
    time::{SystemTime, UNIX_EPOCH},
};

use stern_icon_atlas::{
    Catalog, Discovery, FillRule, NormalizedIcon, NormalizedPath, PathCommand, Snapshot, StrokeCap,
    StrokeJoin, VENDORED_ARCHIVE, Weight, constant_name, normalize_svg,
};

const GENERATED_RELATIVE: &str = "crates/stern-icons-phosphor/src/generated";
const MAX_SHARD_LINES: usize = 640;
const HEADER: &str = "//! Generated by `cargo run -p stern-icon-atlas -- generate`; do not edit.\n\
// Source: @phosphor-icons/core 2.1.1 (pinned and checksum-verified).\n\
#![allow(unused_imports, clippy::unreadable_literal)]\n";

type DynResult<T> = Result<T, Box<dyn std::error::Error>>;
type FileTree = BTreeMap<PathBuf, Vec<u8>>;

#[derive(Default)]
struct Metrics {
    definitions: usize,
    aliases: usize,
    paths: usize,
    elements: usize,
}

pub(crate) fn generate_workspace() -> DynResult<()> {
    let workspace = workspace_root();
    let (tree, metrics) = build_tree(&workspace)?;
    let target = workspace.join(GENERATED_RELATIVE);
    let stage = temporary_directory("stern-phosphor-generate");
    write_tree(&stage, &tree)?;
    sync_from_stage(&stage, &target, &tree)?;
    fs::remove_dir_all(&stage)?;
    print_metrics("generated", &tree, &metrics);
    Ok(())
}

pub(crate) fn check_workspace() -> DynResult<()> {
    let workspace = workspace_root();
    let (tree, metrics) = build_tree(&workspace)?;
    let temporary = temporary_directory("stern-phosphor-check");
    write_tree(&temporary, &tree)?;
    let expected = read_tree(&temporary)?;
    let actual = read_tree(&workspace.join(GENERATED_RELATIVE))?;
    let drift = compare_trees(&expected, &actual);
    fs::remove_dir_all(&temporary)?;
    if !drift.is_empty() {
        return Err(drift.render().into());
    }
    print_metrics("checked", &tree, &metrics);
    Ok(())
}

fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("atlas crate must be inside workspace/crates")
        .to_path_buf()
}

fn build_tree(workspace: &Path) -> DynResult<(FileTree, Metrics)> {
    let snapshot = Snapshot::open(workspace.join(VENDORED_ARCHIVE))?;
    let catalog = Catalog::from_snapshot(&snapshot)?;
    let discovery = Discovery::from_snapshot(&snapshot, &catalog)?;
    let mut tree = FileTree::new();
    let mut metrics = Metrics::default();
    let mut root = String::from(HEADER);
    for weight in Weight::ALL {
        writeln!(root, "pub mod {};", weight.as_str())?;
        generate_weight(
            &snapshot,
            &catalog,
            &discovery,
            weight,
            &mut tree,
            &mut metrics,
        )?;
    }
    tree.insert(PathBuf::from("mod.rs"), root.into_bytes());
    if metrics.definitions != 9_072 || metrics.aliases != 108 {
        return Err(format!(
            "generation count mismatch: {} definitions and {} aliases",
            metrics.definitions, metrics.aliases
        )
        .into());
    }
    Ok((tree, metrics))
}

fn generate_weight(
    snapshot: &Snapshot,
    catalog: &Catalog,
    discovery: &Discovery,
    weight: Weight,
    tree: &mut FileTree,
    metrics: &mut Metrics,
) -> DynResult<()> {
    let directory = PathBuf::from(weight.as_str());
    let mut shards = Vec::<String>::new();
    let mut body = String::from(HEADER);
    body.push_str(
        "use stern_core::{FillRule, IconGraphic, IconId, IconLayer, IconPath, \
IconStroke, PathElement, Point, Rect, StaticIcon, StrokeCap, StrokeJoin};\n",
    );
    body.push_str("use crate::{PhosphorIcon, Weight};\n\n");
    let fixed_lines = line_count(&body);
    for (record, discovered) in catalog.records.iter().zip(&discovery.icons) {
        if record.name != discovered.name {
            return Err("catalog/discovery order diverged".into());
        }
        let asset = discovered
            .assets
            .iter()
            .find(|asset| asset.weight == weight)
            .ok_or_else(|| format!("missing {} asset for {}", weight.as_str(), record.name))?;
        let normalized = normalize_svg(&asset.archive_path, snapshot.text(&asset.archive_path)?)?;
        let fragment = render_definition(
            &record.name,
            record.alias.as_ref().map(|alias| alias.name.as_str()),
            weight,
            asset.stable_id.0,
            &normalized,
            metrics,
        )?;
        let fragment_lines = line_count(&fragment);
        if fixed_lines + fragment_lines > MAX_SHARD_LINES {
            return Err(format!(
                "single generated definition `{}`/{} requires {} lines; shard limit is {}",
                record.name,
                weight.as_str(),
                fixed_lines + fragment_lines,
                MAX_SHARD_LINES
            )
            .into());
        }
        if line_count(&body) + fragment_lines > MAX_SHARD_LINES && line_count(&body) > fixed_lines {
            flush_shard(&directory, &mut body, &mut shards, tree);
            body = String::from(HEADER);
            body.push_str(
                "use stern_core::{FillRule, IconGraphic, IconId, IconLayer, IconPath, \
IconStroke, PathElement, Point, Rect, StaticIcon, StrokeCap, StrokeJoin};\n",
            );
            body.push_str("use crate::{PhosphorIcon, Weight};\n\n");
        }
        body.push_str(&fragment);
    }
    if line_count(&body) > fixed_lines {
        flush_shard(&directory, &mut body, &mut shards, tree);
    }
    let mut module = String::from(HEADER);
    writeln!(
        module,
        "// Shards are packed deterministically to at most {MAX_SHARD_LINES} lines."
    )?;
    for shard in &shards {
        writeln!(module, "mod {shard};")?;
        writeln!(module, "pub use {shard}::*;")?;
    }
    if line_count(&module) > MAX_SHARD_LINES {
        return Err(format!("{} module index exceeds shard line bound", weight.as_str()).into());
    }
    tree.insert(directory.join("mod.rs"), module.into_bytes());
    Ok(())
}

fn flush_shard(directory: &Path, body: &mut String, shards: &mut Vec<String>, tree: &mut FileTree) {
    let name = format!("shard_{:03}", shards.len());
    while body.ends_with("\n\n") {
        body.pop();
    }
    let contents = std::mem::take(body).into_bytes();
    tree.insert(directory.join(format!("{name}.rs")), contents);
    shards.push(name);
}

fn render_definition(
    name: &str,
    alias: Option<&str>,
    weight: Weight,
    id: u64,
    icon: &NormalizedIcon,
    metrics: &mut Metrics,
) -> DynResult<String> {
    let rust = constant_name(name);
    let prefix = rust.clone();
    let mut output = String::new();
    for (index, path) in icon.paths.iter().enumerate() {
        writeln!(
            output,
            "static {prefix}_ELEMENTS_{index}: [PathElement; {}] = [",
            path.commands.len()
        )?;
        for command in &path.commands {
            writeln!(output, "    {},", render_command(command)?)?;
        }
        writeln!(
            output,
            "];\nstatic {prefix}_PATH_{index}: [IconPath; 1] = [IconPath::new("
        )?;
        writeln!(
            output,
            "    &{prefix}_ELEMENTS_{index}, {}, {}, 1.0_f32,",
            render_fill(path),
            render_stroke(path)?
        )?;
        writeln!(output, ")];")?;
        metrics.elements += path.commands.len();
    }
    writeln!(
        output,
        "static {prefix}_LAYERS: [IconLayer; {}] = [",
        icon.paths.len()
    )?;
    for (index, path) in icon.paths.iter().enumerate() {
        writeln!(
            output,
            "    IconLayer::new(&{prefix}_PATH_{index}, {}),",
            f32_literal(path.opacity)?
        )?;
    }
    writeln!(
        output,
        "];\nstatic {prefix}_GRAPHIC: IconGraphic = IconGraphic::new("
    )?;
    writeln!(
        output,
        "    Rect::new(0.0_f32, 0.0_f32, {}, {}), &{prefix}_LAYERS,",
        f32_literal(icon.width)?,
        f32_literal(icon.height)?
    )?;
    writeln!(output, ");")?;
    writeln!(
        output,
        "/// `{name}` in the Phosphor {} weight.",
        weight.as_str()
    )?;
    writeln!(
        output,
        "pub const {rust}: PhosphorIcon = PhosphorIcon::new("
    )?;
    writeln!(
        output,
        "    \"{name}\", Weight::{}, \"STERN_PHOSPHOR_2_1_1:{}:{name}\",",
        weight_variant(weight),
        weight.as_str()
    )?;
    writeln!(
        output,
        "    StaticIcon::new(IconId::from_raw(0x{id:016x}), &{prefix}_GRAPHIC),\n);\n"
    )?;
    if let Some(alias) = alias {
        let alias_rust = constant_name(alias);
        writeln!(
            output,
            "#[deprecated(since = \"1.0.0\", note = \"use `{rust}`\")]\n/// Deprecated upstream alias for [`{rust}`].\npub const {alias_rust}: PhosphorIcon = {rust};\n"
        )?;
        metrics.aliases += 1;
    }
    metrics.definitions += 1;
    metrics.paths += icon.paths.len();
    Ok(output)
}

fn render_command(command: &PathCommand) -> DynResult<String> {
    Ok(match command {
        PathCommand::MoveTo(point) => format!("PathElement::MoveTo({})", render_point(*point)?),
        PathCommand::LineTo(point) => format!("PathElement::LineTo({})", render_point(*point)?),
        PathCommand::QuadTo { control, to } => format!(
            "PathElement::QuadTo {{ ctrl: {}, to: {} }}",
            render_point(*control)?,
            render_point(*to)?
        ),
        PathCommand::CubicTo {
            control1,
            control2,
            to,
        } => format!(
            "PathElement::CubicTo {{ ctrl1: {}, ctrl2: {}, to: {} }}",
            render_point(*control1)?,
            render_point(*control2)?,
            render_point(*to)?
        ),
        PathCommand::Close => "PathElement::Close".to_owned(),
    })
}

fn render_point(point: stern_icon_atlas::Point) -> DynResult<String> {
    Ok(format!(
        "Point::new({}, {})",
        f32_literal(point.x)?,
        f32_literal(point.y)?
    ))
}

fn render_fill(path: &NormalizedPath) -> &'static str {
    if !path.filled {
        return "None";
    }
    match path.fill_rule {
        FillRule::NonZero => "Some(FillRule::NonZero)",
        FillRule::EvenOdd => "Some(FillRule::EvenOdd)",
    }
}

fn render_stroke(path: &NormalizedPath) -> DynResult<String> {
    let Some(stroke) = path.stroke else {
        return Ok("None".to_owned());
    };
    Ok(format!(
        "Some(IconStroke::new({}, StrokeCap::{}, StrokeJoin::{}))",
        f32_literal(stroke.width)?,
        cap_variant(stroke.cap),
        join_variant(stroke.join)
    ))
}

#[allow(clippy::cast_possible_truncation)]
fn f32_literal(value: f64) -> DynResult<String> {
    if !value.is_finite() {
        return Err("cannot generate a non-finite f64".into());
    }
    if !(-f64::from(f32::MAX)..=f64::from(f32::MAX)).contains(&value) {
        return Err(format!("f64 value {value} overflows f32").into());
    }
    // Narrowing is the format boundary; finite/range checks above make it explicit.
    let narrowed = value as f32;
    if !narrowed.is_finite() {
        return Err(format!("f64 value {value} overflows f32").into());
    }
    let narrowed = if narrowed == 0.0 { 0.0 } else { narrowed };
    Ok(format!("{narrowed:?}_f32"))
}

fn weight_variant(weight: Weight) -> &'static str {
    match weight {
        Weight::Thin => "Thin",
        Weight::Light => "Light",
        Weight::Regular => "Regular",
        Weight::Bold => "Bold",
        Weight::Fill => "Fill",
        Weight::Duotone => "Duotone",
    }
}
fn cap_variant(cap: StrokeCap) -> &'static str {
    match cap {
        StrokeCap::Butt => "Butt",
        StrokeCap::Round => "Round",
        StrokeCap::Square => "Square",
    }
}
fn join_variant(join: StrokeJoin) -> &'static str {
    match join {
        StrokeJoin::Miter => "Miter",
        StrokeJoin::Round => "Round",
        StrokeJoin::Bevel => "Bevel",
    }
}

fn line_count(value: &str) -> usize {
    value.lines().count()
}

fn temporary_directory(label: &str) -> PathBuf {
    let nonce = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    std::env::temp_dir().join(format!("{label}-{}-{nonce}", std::process::id()))
}

fn write_tree(root: &Path, tree: &FileTree) -> io::Result<()> {
    for (relative, contents) in tree {
        let path = root.join(relative);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(path, contents)?;
    }
    Ok(())
}

fn sync_from_stage(stage: &Path, target: &Path, expected: &FileTree) -> io::Result<()> {
    fs::create_dir_all(target)?;
    let actual = read_tree(target)?;
    for relative in expected.keys() {
        let source = stage.join(relative);
        let destination = target.join(relative);
        if let Some(parent) = destination.parent() {
            fs::create_dir_all(parent)?;
        }
        if fs::read(&destination).ok().as_deref() != expected.get(relative).map(Vec::as_slice) {
            fs::copy(source, destination)?;
        }
    }
    // Remove obsolete files only after every expected replacement is present.
    for relative in actual.keys().filter(|path| !expected.contains_key(*path)) {
        fs::remove_file(target.join(relative))?;
    }
    remove_empty_directories(target)?;
    Ok(())
}

fn read_tree(root: &Path) -> io::Result<FileTree> {
    let mut tree = FileTree::new();
    if root.exists() {
        read_directory(root, root, &mut tree)?;
    }
    Ok(tree)
}

fn read_directory(root: &Path, directory: &Path, tree: &mut FileTree) -> io::Result<()> {
    let mut entries = fs::read_dir(directory)?.collect::<Result<Vec<_>, _>>()?;
    entries.sort_by_key(std::fs::DirEntry::file_name);
    for entry in entries {
        let path = entry.path();
        if path.is_dir() {
            read_directory(root, &path, tree)?;
        } else {
            tree.insert(
                path.strip_prefix(root).expect("descendant").to_path_buf(),
                fs::read(path)?,
            );
        }
    }
    Ok(())
}

fn remove_empty_directories(root: &Path) -> io::Result<bool> {
    let mut empty = true;
    for entry in fs::read_dir(root)?.collect::<Result<Vec<_>, _>>()? {
        let path = entry.path();
        if path.is_dir() {
            if remove_empty_directories(&path)? {
                fs::remove_dir(path)?;
            } else {
                empty = false;
            }
        } else {
            empty = false;
        }
    }
    Ok(empty)
}

#[derive(Debug, Default, Eq, PartialEq)]
struct Drift {
    changed: Vec<PathBuf>,
    missing: Vec<PathBuf>,
    unexpected: Vec<PathBuf>,
}

impl Drift {
    fn is_empty(&self) -> bool {
        self.changed.is_empty() && self.missing.is_empty() && self.unexpected.is_empty()
    }
    fn render(&self) -> String {
        let mut output = String::from("generated source drift detected:\n");
        for (label, paths) in [
            ("changed", &self.changed),
            ("missing", &self.missing),
            ("unexpected", &self.unexpected),
        ] {
            for path in paths {
                writeln!(output, "{label}: {}", path.display()).expect("String write");
            }
        }
        output
    }
}

fn compare_trees(expected: &FileTree, actual: &FileTree) -> Drift {
    let expected_paths = expected.keys().cloned().collect::<BTreeSet<_>>();
    let actual_paths = actual.keys().cloned().collect::<BTreeSet<_>>();
    Drift {
        changed: expected_paths
            .intersection(&actual_paths)
            .filter(|path| expected.get(*path) != actual.get(*path))
            .cloned()
            .collect(),
        missing: expected_paths.difference(&actual_paths).cloned().collect(),
        unexpected: actual_paths.difference(&expected_paths).cloned().collect(),
    }
}

fn print_metrics(verb: &str, tree: &FileTree, metrics: &Metrics) {
    let source_bytes = tree.values().map(Vec::len).sum::<usize>();
    let estimated_data = metrics.elements * 28 + metrics.paths * 56 + metrics.definitions * 80;
    println!(
        "{verb} {} files: {} definitions, {} aliases, {} paths, {} elements, {source_bytes} source bytes, approximately {estimated_data} static data bytes",
        tree.len(),
        metrics.definitions,
        metrics.aliases,
        metrics.paths,
        metrics.elements
    );
}

#[cfg(test)]
mod tests {
    use super::{
        FileTree, GENERATED_RELATIVE, MAX_SHARD_LINES, compare_trees, f32_literal, read_tree,
        workspace_root,
    };
    use std::{fs, path::PathBuf};

    fn tree(items: &[(&str, &[u8])]) -> FileTree {
        items
            .iter()
            .map(|(path, bytes)| (PathBuf::from(path), bytes.to_vec()))
            .collect()
    }

    #[test]
    fn drift_diagnostics_are_separate_and_sorted() {
        let expected = tree(&[("z.rs", b"new"), ("m.rs", b"missing"), ("a.rs", b"same")]);
        let actual = tree(&[("z.rs", b"old"), ("x.rs", b"extra"), ("a.rs", b"same")]);
        let drift = compare_trees(&expected, &actual);
        assert_eq!(drift.changed, vec![PathBuf::from("z.rs")]);
        assert_eq!(drift.missing, vec![PathBuf::from("m.rs")]);
        assert_eq!(drift.unexpected, vec![PathBuf::from("x.rs")]);
        assert_eq!(
            drift.render(),
            "generated source drift detected:\nchanged: z.rs\nmissing: m.rs\nunexpected: x.rs\n"
        );
    }

    #[test]
    fn float_conversion_is_finite_and_explicit() {
        assert_eq!(f32_literal(1.25).expect("finite"), "1.25_f32");
        assert!(f32_literal(f64::INFINITY).is_err());
        assert!(f32_literal(f64::MAX).is_err());
        assert_eq!(MAX_SHARD_LINES, 640);
    }

    #[test]
    fn checked_in_shards_obey_bounds_and_runtime_boundary() {
        let workspace = workspace_root();
        let generated = read_tree(&workspace.join(GENERATED_RELATIVE)).expect("generated tree");
        assert_eq!(generated.len(), 1_084);
        for (path, bytes) in &generated {
            let source = std::str::from_utf8(bytes).expect("generated UTF-8");
            assert!(
                source.lines().count() <= MAX_SHARD_LINES,
                "{}",
                path.display()
            );
            assert!(source.contains("Generated by `cargo run -p stern-icon-atlas -- generate`"));
            for forbidden in [
                "Vec<",
                "String",
                "std::fs",
                "HashMap",
                "BTreeMap",
                "OnceLock",
                "LazyLock",
                "include_bytes!",
            ] {
                assert!(
                    !source.contains(forbidden),
                    "{} contains {forbidden}",
                    path.display()
                );
            }
        }
        let manifest = fs::read_to_string(workspace.join("crates/stern-icons-phosphor/Cargo.toml"))
            .expect("runtime manifest");
        assert!(manifest.contains("stern-core = { path = \"../stern-core\" }"));
        assert!(!manifest.contains("stern-icon-atlas"));
        assert!(
            !workspace
                .join("crates/stern-icons-phosphor/build.rs")
                .exists()
        );
    }
}
