[package]
name = "stern"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Application-facing facade for the Stern desktop toolkit"

[features]
default = ["platform-winit", "render-vello", "vello-winit"]
platform-winit = ["dep:stern-winit"]
render-vello = ["dep:stern-vello"]
vello-winit = ["platform-winit", "render-vello", "dep:stern-vello-winit"]

[dependencies]
stern-core = { version = "=0.2.0-alpha.1", path = "../stern-core" }
stern-render = { version = "=0.2.0-alpha.1", path = "../stern-render" }
stern-text = { version = "=0.2.0-alpha.1", path = "../stern-text" }
stern-widgets = { version = "=0.2.0-alpha.1", path = "../stern-widgets" }
stern-winit = { version = "=0.2.0-alpha.1", path = "../stern-winit", optional = true }
stern-vello = { version = "=0.2.0-alpha.1", path = "../stern-vello", optional = true }
stern-vello-winit = { version = "=0.2.0-alpha.1", path = "../stern-vello-winit", optional = true }

[dev-dependencies]
stern-icons-phosphor = { version = "=0.2.0-alpha.1", path = "../stern-icons-phosphor" }

[lints]
workspace = true
